### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by mivalsten** [jrich523/NimblePowerShell#17]
Hi @jrich523 
I would like to use part of your code (New-DynamicParam function from utility.ps1) in my project, but for now I can't due to lack of license. Would you be ok in granting me one-time permission or more generally assigning some license to your work?

Best Regards,
Grzegorz

**Comment by jrich523** [comment]
bah just copy it from a blog post, no lic required ;)

https://jrich523.wordpress.com/2013/05/30/powershell-simple-way-to-add-dynamic-parameters-to-advanced-function/
